channels:
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- lightgbm=2.1.0=py36_0
- ncurses=5.9=10
- numpy=1.14.2=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- pip=9.0.2=py36_0
- python=3.6.4=0
- python-dateutil=2.7.0=py_0
- pytz=2018.3=py_0
- readline=7.0=0
- scikit-learn=0.19.1=py36_blas_openblas_201
- scipy=1.0.0=py36_blas_openblas_201
- setuptools=39.0.1=py36_0
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- tqdm=4.21.0=py_0
- wheel=0.30.0=py36_2
- xz=5.2.3=0
- zlib=1.2.11=0
- libgfortran=3.0.0=1
