channels:
- conda-forge
- defaults
dependencies:
- altair=1.2.1=py_0
- backcall=0.1.0=py_0
- blas=1.1=openblas
- bleach=2.1.3=py_0
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- decorator=4.2.1=py36_0
- entrypoints=0.2.3=py36_1
- expat=2.2.5=0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- gettext=0.19.8.1=0
- glib=2.55.0=0
- gmp=6.1.2=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- html5lib=1.0.1=py_0
- icu=58.2=0
- ipykernel=4.8.2=py36_0
- ipython=6.3.1=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_1
- jupyter_client=5.2.3=py36_0
- jupyter_core=4.4.0=py_0
- kiwisolver=1.0.1=py36_1
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.34=0
- libsodium=1.0.16=0
- libxcb=1.13=0
- libxml2=2.9.8=0
- lightgbm=2.1.0=py36_0
- markupsafe=1.0=py36_0
- matplotlib=2.2.2=py36_1
- mistune=0.8.3=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.4.1=py36_0
- numpy=1.14.2=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- pandoc=2.1.3=0
- pandocfilters=1.4.1=py36_0
- parso=0.1.1=py_0
- pcre=8.41=1
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.3=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.5=1
- python-dateutil=2.7.2=py_0
- pytz=2018.3=py_0
- pyzmq=17.0.0=py36_4
- qt=5.6.2=7
- readline=7.0=0
- scikit-learn=0.19.1=py36_blas_openblas_201
- scipy=1.0.1=py36_blas_openblas_200
- send2trash=1.5.0=py_0
- setuptools=39.0.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tk=8.6.7=0
- tornado=5.0.2=py36_0
- tqdm=4.21.0=py_0
- traitlets=4.3.2=py36_0
- vega=0.4.4=py36_1
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.31.0=py36_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zeromq=4.2.5=1
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- pip:
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.3
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
